version: '3.8'

services:
  api:
    build:
      context: ./api
    image: hiuston007/capstone-api
    container_name: api
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./front-end-nextjs
    image: hiuston007/capstone-frontend
    container_name: nextjs
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always

